spring:
  jpa:
    hibernate.hbm2ddl.auto: create-drop
    hibernate.show_sql: true
  datasource:
    url: jdbc:sqlite:file:myDb.db?cache=shared
    username: root
    password: root
  h2:
    console.enabled: true
  flyway:
    baseline-on-migrate: true
#    schemas: myDb
    enabled: true
    url: jdbc:sqlite:file:myDb.db?cache=shared
    user: root
    password: root
    validate-on-migrate: true
    locations: "classpath:db/migration"